FROM wordpress:6-php8.2-apache

# Install wp-cli
RUN curl -sO https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x wp-cli.phar \
    && mv wp-cli.phar /usr/local/bin/wp

# Apache strips the Authorization header by default -- needed for WP REST API Basic auth
RUN echo 'SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1' > /etc/apache2/conf-available/pass-authorization.conf \
    && a2enconf pass-authorization \
    && a2enmod rewrite headers

# Allow Application Passwords over HTTP (dev only -- WP requires SSL by default)
RUN mkdir -p /usr/src/wordpress/wp-content/mu-plugins \
    && echo '<?php add_filter("wp_is_application_passwords_available", "__return_true");' \
       > /usr/src/wordpress/wp-content/mu-plugins/allow-app-pw.php
