events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server { listen 80; server_name author1.htmltrust.test; location / { proxy_pass http://wp-1:80; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; } }
    server { listen 80; server_name author2.htmltrust.test; location / { proxy_pass http://wp-2:80; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; } }
    server { listen 80; server_name author3.htmltrust.test; root /var/www/hugo/author3; index index.html; location / { try_files $uri $uri/ =404; } }

    server { listen 80 default_server; return 404; }
}
