events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server { listen 80; server_name author1.htmltrust.test; location / { proxy_pass http://wp-1:80; proxy_set_header Host $host; } }
    server { listen 80; server_name author2.htmltrust.test; location / { proxy_pass http://wp-2:80; proxy_set_header Host $host; } }
    server { listen 80; server_name author3.htmltrust.test; location / { proxy_pass http://wp-3:80; proxy_set_header Host $host; } }
    server { listen 80; server_name author4.htmltrust.test; location / { proxy_pass http://wp-4:80; proxy_set_header Host $host; } }
    server { listen 80; server_name author5.htmltrust.test; location / { proxy_pass http://wp-5:80; proxy_set_header Host $host; } }

    server { listen 80; server_name author6.htmltrust.test;  root /var/www/hugo/author6;  index index.html; location / { try_files $uri $uri/ =404; } }
    server { listen 80; server_name author7.htmltrust.test;  root /var/www/hugo/author7;  index index.html; location / { try_files $uri $uri/ =404; } }
    server { listen 80; server_name author8.htmltrust.test;  root /var/www/hugo/author8;  index index.html; location / { try_files $uri $uri/ =404; } }
    server { listen 80; server_name author9.htmltrust.test;  root /var/www/hugo/author9;  index index.html; location / { try_files $uri $uri/ =404; } }
    server { listen 80; server_name author10.htmltrust.test; root /var/www/hugo/author10; index index.html; location / { try_files $uri $uri/ =404; } }

    server { listen 80 default_server; return 404; }
}
